import { NextPageContext } from 'next'
import Head from 'next/head'
import { useQuery } from '../hooks';

export default function Query() {
  const { isLoading, error, data } = useQuery(async () => {
    const rsp = await fetch('/api/q' + window.location.pathname)
    const json = await rsp.json();
    return rsp.ok ? json.result : json.message;
  })

  return (
    <div >
      <Head>
        <title>gm</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="md:absolute md:left-1/2 md:-translate-x-1/2 md:w-3/5 max-w-[800px] md:mt-8 md:rounded-md sm:m-2 bg-white p-6">
        {isLoading && <div>Loading...</div>}
        {error && <div>Error: {error.message}</div>}
        {data && <div className='break-words font-mono'>{data}</div>}
      </main>
    </div>
  )
}

